### ISSUE TITLE
nefunguje

### ISSUE THREAD

**Issue by jankratochvil** [peci1/vfpark-export-all#1]
ONDOWNLOAD command was used but no download occured., line: 4 (Error code -804)
Taky mi Vodafone pořád vyskakuje, že stránka vypršela.
A ptalo se mě to, co mám s daným CSV udělat, tak jsem clicknul, že uložit a že to dělat vždy.
Jdu to naclickat ručně...

**Comment by peci1** [comment]
A nechal jste prvne na strance se schrankami plne nacist prvni stranku? To vzdycky trva (i nekolik minut). Poustite to ve Firefoxu?

**Comment by jankratochvil** [comment]
Jo, načtená je, tj. zobrazuje těch 100 zpráv. Vím, že to někdy trvá. Ano, firefox-50.1.0-1.fc25.x86_64 (není nejnovější, vzal jsem starší virtual machine, ale to snad nevadí).

**Comment by peci1** [comment]
Tak tomu nerozumim... Zkusil jsem ted skript na uplne jinem pocitaci, dokonce i v Google chrome skript funguje.

Rucni kliknuti na export do CSV funguje?

**Comment by jankratochvil** [comment]
OK, zkusím ještě Chromium, to mě nenapadlo.
Tomu ručnímu clicknutí nerozumím, vždyť ten script si to sám exportuje a pak se to zastaví s chybou.

**Comment by peci1** [comment]
Tim jsem myslel, jestli jste na to "tlacitko" klikal i rucne (bez skriptu). Pokud by hazelo chybu i pri rucnim pouziti, pak samozrejme skript nic nezmuze

**Comment by jankratochvil** [comment]
Ručně to samozřejmě funguje. Akorát se mi nechce ručně clickat každých 100 SMS.  I když by to tedy bylo již hotové rychleji než debuggovat tento script. :-)

**Comment by peci1** [comment]
V tom pripade mi prijde nejjednodussi, abyste si skript zkusil vytvorit ve svem prohlizeci sam. Treba se v necem lisi. Nahravani skriptu v iMacros neni tezke, v zasade staci zapnout nahravani a udelat jednu serii "kliknu na export, ulozim, kliknu na Nasledujici".

Pokud si skript vytvorite a bude fungovat, muzete ho sem prosim nasdilet, abych je mohl porovnat?

**Comment by jankratochvil** [comment]
Bylo to 38 exportů naclickaných za 10 minut, sorry.
